# SPDX-License-Identifier: MPL-2.0

networks:
  rawpair:
    name: rawpair

services:
  db:
    networks:
      - rawpair
    image: postgres:15
    container_name: rawpair_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rawpair_dev
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  yjs:
    networks:
      - rawpair
    build:
      context: ./yjs-server
    container_name: rawpair_yjs
    environment:
      - HOST=0.0.0.0
      - PORT=1234
    ports:
      - "1234:1234"

  nginx:
    networks:
      - rawpair
    image: nginx:stable
    container_name: rawpair_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  loki:
    networks:
      - rawpair
    image: grafana/loki:2.9.4
    container_name: rawpair_loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped

  grafana:
    networks:
      - rawpair
    image: grafana/grafana-oss:10.3.1
    container_name: rawpair_grafana
    ports:
      - "3000:3000"
    depends_on:
      - loki
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  pgdata:
  grafana_data:
  portainer_data:
