# SPDX-License-Identifier: MPL-2.0
#
# IMPORTANT: This playbook assumes that the Cloudflare tunnel has already
# been authenticated and created manually using:
#
#   cloudflared login
#   cloudflared tunnel create rawpair
#
# This will generate ~/.cloudflared/cert.pem and register the tunnel with your
# Cloudflare account. You can then proceed to use this playbook to automate
# the installation and setup of the systemd tunnel service.

- name: cloudflared installation
  hosts: vps
  become: yes
  vars:
    user: your-user
    os: bookworm

  tasks:
    - name: Ensure /etc/apt/keyrings exists
      file:
        path: /usr/share/keyrings
        state: directory
        mode: '0755'

    - name: Download Cloudflare GPG key
      shell: |
        curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg | sudo tee /usr/share/keyrings/cloudflare-main.gpg >/dev/null

    - name: Set permissions on Cloudflare GPG key
      file:
        path: /usr/share/keyrings/cloudflare-main.gpg
        mode: '0644'

    - name: Add Cloudflare apt repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared {{ ansible_distribution_release | lower }} main"
        state: present
        filename: cloudflared

    - name: Install cloudflared
      apt:
        name: cloudflared
        state: present
        update_cache: yes