# SPDX-License-Identifier: MPL-2.0

- name: Install Docker Engine from Docker's official repository
  hosts: vps
  become: yes
  vars:
    user: your-user
    os: debian

  tasks:
    - name: Remove system Docker packages (if any)
      apt:
        name: "{{ item }}"
        state: absent
      loop:
        - docker
        - docker.io
        - docker-doc
        - docker-compose
        - podman-docker
        - containerd
        - runc

    - name: Install prerequisites
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Ensure /etc/apt/keyrings exists
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download and dearmor Docker GPG key
      shell: |
        curl -fsSL https://download.docker.com/linux/{{ os }}/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Set permissions on Docker GPG key
      file:
        path: /etc/apt/keyrings/docker.gpg
        mode: '0644'

    - name: Add Docker APT repository
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/{{ os }} {{ ansible_distribution_release | lower }} stable"
        state: present
        filename: docker

    - name: Install Docker Engine and Compose
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Ensure user is in docker group
      user:
        name: "{{ user }}"
        groups: docker
        append: yes

    - name: Enable Docker service
      systemd:
        name: docker
        enabled: yes
        state: started