# SPDX-License-Identifier: MPL-2.0
- name: RawPair Ubuntu Deployment
  hosts: rawpair
  become: yes
  vars:
    user: your-user
    rawpair_dir: "/home/{{ user }}/rawpair"
    database_url: "postgres://postgres:postgres@localhost/rawpair_dev"
    secret_key_base: "SV/7XaCy1K3ZxDqgRZluV0IfgHaSmD5oC1mVCH5vEd2ZWFmJERcSwadMOfvl1o5H"
    phx_host: "localhost"
    port: 4000
    rawpair_host: "localhost"
    rawpair_port: 4000
    terminal_host: "localhost"
    terminal_port: 8080
    grafana_host: "localhost"
    grafana_port: 3000

  tasks:
    - name: Ensure required packages are installed
      apt:
        name:
          - ufw
        state: present
        update_cache: yes

    - name: Create .env file from template
      template:
        src: env.j2
        dest: "{{ rawpair_dir }}/phoenix-app/.env"
        mode: '0600'

    - name: Create systemd service for rawpair-infra (no-postgres)
      copy:
        dest: /etc/systemd/system/rawpair-infra.service
        content: |
          [Unit]
          Description=RawPair Supporting Infrastructure
          Requires=docker.service
          After=docker.service

          [Service]
          Type=oneshot
          RemainAfterExit=yes
          WorkingDirectory={{ rawpair_dir }}
          ExecStart=/usr/bin/docker compose -f docker-compose.no-postgres.yml up -d
          ExecStop=/usr/bin/docker compose -f docker-compose.no-postgres.yml down
          TimeoutStartSec=0

          [Install]
          WantedBy=multi-user.target

    - name: Reload and enable infra service
      systemd:
        daemon_reload: yes
        name: rawpair-infra
        enabled: yes
        state: started

    - name: Create systemd service for rawpair Phoenix app
      copy:
        dest: /etc/systemd/system/rawpair.service
        content: |
          [Unit]
          Description=RawPair Phoenix App
          After=network.target

          [Service]
          User={{ user }}
          WorkingDirectory={{ rawpair_dir }}/phoenix-app/_build/prod/rel/rawpair
          ExecStart=/bin/bash {{ rawpair_dir }}/phoenix-app/start.sh
          ExecStop=/bin/bash {{ rawpair_dir }}/phoenix-app/stop.sh
          Restart=always
          Environment=PHX_SERVER=true
          Environment=MIX_ENV=prod

          [Install]
          WantedBy=multi-user.target

    - name: Reload and enable Phoenix app service
      systemd:
        daemon_reload: yes
        name: rawpair
        enabled: yes
        state: started

    
