name: Build and release RawPair .deb for amd64 and arm64

on:
  push:
    tags:
      - 'v*'

jobs:
  build-amd64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Elixir + Erlang
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.18.3'
          otp-version: '27.3.2'

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Build RawPair CLI
        run: |
          cd cli
          go build -o ../rawpair-cli

      - name: Install packaging dependencies
        run: sudo apt-get install -y ruby ruby-dev build-essential libssl-dev && sudo gem install --no-document fpm

      - name: Build RawPair .deb for amd64
        run: make ARCH=amd64 RAW_VERSION=${{ github.ref_name }}

      - name: Upload .deb to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

  build-arm64:
    runs-on: [self-hosted, linux, arm64]
    env:
      ImageOS: ubuntu22

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Elixir + Erlang
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.18.3'
          otp-version: '27.3.2'

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Build RawPair CLI
        run: |
          cd cli
          go build -o ../rawpair-cli

      - name: Install packaging dependencies
        run: sudo apt-get install -y ruby ruby-dev build-essential libssl-dev && sudo gem install --no-document fpm

      - name: Build RawPair .deb for arm64
        run: make ARCH=arm64 RAW_VERSION=${{ github.ref_name }}

      - name: Upload .deb to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
